// Auto-generated imports
import {
  isFootnoteBoilerplateElement,
  isFootnoteElement,
} from './footnotes.js';
import {
  isPdfSidePanelElement,
} from './alignment.js';
import {
  BLOCK_SELECTOR,
  SPAN_TAGS,
} from './constants.js';


function spanType(tag) {
  if (tag === 'a') return 'a';
  if (tag === 'strong' || tag === 'b') return 'strong';
  if (tag === 'span') return 'span';
  if (tag === 'sup') return 'sup';
  if (tag === 'sub') return 'sub';
  return 'em';
}

function isAutoGeneratedImageAlt(text) {
  if (!text) return false;
  const norm = text
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  // Common Microsoft Word / Office AI auto-generated alt text patterns
  if (
    norm.includes('description generee automatiquement') ||
    norm.includes('description automatiquement generee') ||
    norm.includes('description automatically generated') ||
    norm.includes('texte genere automatiquement') ||
    norm.includes('image generee automatiquement') ||
    norm.includes('objet genere automatiquement') ||
    norm.includes('icone generee automatiquement') ||
    norm.includes('description generee par') ||
    norm.includes('description generated with')
  ) {
    return true;
  }

  // Word auto-generated shape / graphic alt text (e.g. alert box icons or banner bars)
  if (
    /^un objet (?:rectangulaire|carre|circulaire|de forme|graphique)/i.test(norm) ||
    /^une forme (?:rectangulaire|carree|circulaire|geometrique)/i.test(norm) ||
    /^une image contenant (?:un objet|du texte|une icone|un logo)/i.test(norm) ||
    /^a (?:rectangular|square|circular) object/i.test(norm) ||
    /^a picture containing (?:an object|text|an icon|a logo)/i.test(norm) ||
    /^a screenshot of/i.test(norm)
  ) {
    return true;
  }

  return false;
}

function isDecorativeOrAutoGeneratedElement(el) {
  if (!el || !el.tagName) return false;
  const tag = el.tagName.toLowerCase();
  if (tag === 'img') {
    const alt = el.getAttribute('alt') || '';
    const src = el.getAttribute('src') || '';
    if ((!src || src.startsWith('data:')) && isAutoGeneratedImageAlt(alt)) return true;
  }
  return false;
}

function isLeafBlock(el) {
  if (el.classList && el.classList.contains('gc-br-line')) {
    return true;
  }
  if (el.querySelector && el.querySelector('.gc-br-line')) {
    return false;
  }
  const tagName = el.tagName.toLowerCase();
  if (tagName === 'img') {
    return true;
  }
  if (['input', 'textarea', 'button'].includes(tagName)) return true;

  if (tagName === 'li') {
    // If this <li> contains child content block elements (such as <p>, <div>, <blockquote>, etc.)
    // that are inside this <li> but NOT part of a nested sub-list <ul> or <ol>,
    // then this <li> is a structural container and those inner <p> elements are the leaf blocks.
    const nonListChildBlocks = Array.from(el.querySelectorAll(BLOCK_SELECTOR)).filter((child) => {
      if (child === el) return false;
      if (isFootnoteBoilerplateElement(child) || isDecorativeOrAutoGeneratedElement(child)) return false;
      const childTag = child.tagName.toLowerCase();
      if (childTag === 'ul' || childTag === 'ol') return false;
      const nestedList = child.closest('ul, ol');
      if (nestedList && el.contains(nestedList) && nestedList !== el.parentElement) {
        return false;
      }
      return true;
    });

    if (nonListChildBlocks.length > 0) {
      return false;
    }
    return true;
  }

  // If it contains child blocks, check if those child blocks are actual content blocks (not just boilerplate or decorative images)
  const childBlocks = Array.from(el.querySelectorAll(BLOCK_SELECTOR)).filter(
    (child) => child !== el && !isFootnoteBoilerplateElement(child) && !isDecorativeOrAutoGeneratedElement(child)
  );
  return childBlocks.length === 0;
}

function isClassificationMarking(text) {
  const words = text
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  if (!words.length || words.length > 6) return false;
  const allowed = new Set([
    'unclassified', 'non', 'classifie', 'classifiee', 'protected',
    'protege', 'a', 'b', 'c', 'secret', 'top', 'confidential', 'confidentiel'
  ]);
  const core = [
    'unclassified', 'classifie', 'classifiee', 'protected',
    'protege', 'secret', 'confidential', 'confidentiel'
  ];
  return words.every((w) => allowed.has(w)) && words.some((w) => core.includes(w));
}

function isPlainUrlText(text) {
  const t = text.trim().replace(/[.,;:)\]\u00bb]+$/, '');
  if (!t) return false;
  return /^(https?:\/\/\S+|www\.\S+)$/i.test(t);
}

function cleanThTags(root) {
  if (!root) return;
  const thElements = root.querySelectorAll ? root.querySelectorAll('th') : [];
  thElements.forEach((th) => {
    th.querySelectorAll('strong, b').forEach((boldEl) => {
      const parent = boldEl.parentNode;
      if (parent) {
        while (boldEl.firstChild) {
          parent.insertBefore(boldEl.firstChild, boldEl);
        }
        parent.removeChild(boldEl);
      }
    });
  });
}

// Table captions carry their own emphasis — unwrap any redundant <strong>/<b>
// inside <caption> (keeps the text, drops the tag). Covers root itself being
// a caption (per-block cleanup) as well as captions anywhere underneath.
function cleanCaptionTags(root) {
  if (!root || !root.querySelectorAll) return;
  const scopes = [];
  if (root.tagName && root.tagName.toLowerCase() === 'caption') scopes.push(root);
  root.querySelectorAll('caption').forEach((c) => scopes.push(c));
  scopes.forEach((cap) => {
    cap.querySelectorAll('strong, b').forEach((boldEl) => {
      const parent = boldEl.parentNode;
      if (parent) {
        while (boldEl.firstChild) {
          parent.insertBefore(boldEl.firstChild, boldEl);
        }
        parent.removeChild(boldEl);
      }
    });
  });
}

function getBlockContent(el) {
  if (!el) return "";
  const tag = el.tagName ? el.tagName.toLowerCase() : "";
  if (tag === "img") {
    const alt = (el.getAttribute("alt") || "").trim();
    if (alt && !isAutoGeneratedImageAlt(alt)) return alt;
    if (isPdfSidePanelElement(el)) {
      return (el.getAttribute("src") || "").trim() || "Publication cover thumbnail";
    }
    return "";
  }
  if (["input", "textarea"].includes(tag) && el.hasAttribute("placeholder"))
    return el.getAttribute("placeholder") || "";
  if (["input", "button"].includes(tag) && el.hasAttribute("aria-label"))
    return el.getAttribute("aria-label") || "";
  
  const clone = el.cloneNode(true);
  clone.querySelectorAll("ul, ol").forEach((childList) => childList.remove());
  clone.querySelectorAll(".fn-rtn, a[href*=\"-rf\"]").forEach((rtn) => rtn.remove());
  clone.querySelectorAll(".wb-inv").forEach((inv) => {
    if (/Footnote|Note de bas de page|Return to footnote|Retour à la référence/i.test(inv.textContent)) {
      inv.remove();
    }
  });
  clone.querySelectorAll("br").forEach((br) => {
    const doc = clone.ownerDocument || document;
    br.replaceWith(doc.createTextNode("\n"));
  });
  return (clone.textContent || "")
    .replace(/[ \t\r]+/g, " ")
    .replace(/[ \t]*\n[ \t]*/g, "\n")
    .trim();
}

function extractBlockSpans(el) {
  const isBrLine = el.classList && el.classList.contains('gc-br-line');
  const tag = el.tagName.toLowerCase();
  if (SPAN_TAGS.includes(tag) && !isBrLine) {
    if (isFootnoteElement(el)) return [];
    const type = spanType(tag);
    return [
      {
        type,
        text: (el.textContent || '').replace(/[ \t\r\n]+/g, ' ').trim(),
        href: type === 'a' ? el.getAttribute('href') || '' : undefined,
        lang: el.getAttribute('lang') || undefined,
        start: 0,
      },
    ];
  }
  const found = Array.from(el.querySelectorAll(SPAN_TAGS.join(', '))).filter(
    (n) => !isFootnoteElement(n) && !n.closest('ul, ol')?.parentElement?.closest(el.tagName) === false && (!n.closest('ul, ol') || n.closest('ul, ol') === el.closest('ul, ol'))
  );
  // Specifically: if `el` contains child lists (`<ul>` or `<ol>`), ignore any span inside those child lists
  // Chrome nested inside a citation is part of the citation, not prose: the
  // "Note de bas de page " label of a marker lives in a .wb-inv span, and
  // recording it would let the words be matched into the translated text.
  const insideFootnote = (n) => {
    let p = n;
    while (p && p !== el) {
      if (isFootnoteElement(p)) return true;
      p = p.parentElement;
    }
    return false;
  };
  const filteredFound = Array.from(el.querySelectorAll(SPAN_TAGS.join(', '))).filter((n) => {
    if (isFootnoteElement(n) || insideFootnote(n)) return false;
    // A superscript cross-reference (<sup><a href="#table1">1</a></sup>) keeps
    // the link and loses the raised formatting, exactly as before <sup> became
    // a span type. A navigable link is worth more than the vertical offset, and
    // the top-level pass would otherwise let the <sup> swallow the anchor.
    if (n.tagName && n.tagName.toLowerCase() === 'sup' && n.querySelector('a')) return false;
    // Check if `n` is inside a child list that is nested inside `el`
    const childList = n.closest('ul, ol');
    if (childList && el.contains(childList) && childList !== el) {
      return false;
    }
    return true;
  });
  const foundSet = new Set(filteredFound);
  const topLevel = filteredFound.filter((n) => {
    let p = n.parentElement;
    while (p && p !== el) {
      if (foundSet.has(p)) return false;
      p = p.parentElement;
    }
    return true;
  });
  // Record each span's character offset within the block text so repeated
  // words can be re-pinned to the right occurrence when spans are applied
  // to translated text (see replaceBlockTextPreservingLinks).
  const spanStarts = spanStartOffsets(el, topLevel);
  return topLevel
    .map((n, idx) => {
      const type = spanType(n.tagName.toLowerCase());
      return {
        type,
        text: (n.textContent || '').replace(/[ \t\r\n]+/g, ' ').trim(),
        href: type === 'a' ? n.getAttribute('href') || '' : undefined,
        lang: n.getAttribute('lang') || undefined,
        start: spanStarts[idx],
      };
    })
    .filter((s) => s.text.length > 0);
}

// Collapse whitespace exactly like getBlockContent so offsets share its
// coordinate space (trailing trim handled by the caller via leadingWs).
function normalizeSpanScopeText(s) {
  return (s || '').replace(/[ \t\r]+/g, ' ').replace(/[ \t]*\n[ \t]*/g, '\n');
}

// Character offset of each span node within the block text. Returns null per
// span when it cannot be measured (caller falls back to first-match).
function spanStartOffsets(el, spanNodes) {
  const starts = new Array(spanNodes.length).fill(null);
  if (!spanNodes.length || !el) return starts;
  try {
    const doc = el.ownerDocument || (typeof document !== 'undefined' ? document : null);
    if (!doc || typeof doc.createRange !== 'function') return starts;
    // getBlockContent trims the block text: measure the trimmed-away leading
    // whitespace once so offsets land in trimmed coordinates.
    const fullRange = doc.createRange();
    fullRange.selectNodeContents(el);
    const leadingWs = (normalizeSpanScopeText(fullRange.toString()).match(/^\s*/) || [''])[0].length;
    spanNodes.forEach((n, i) => {
      try {
        const r = doc.createRange();
        r.setStart(el, 0);
        r.setEnd(n, 0);
        starts[i] = Math.max(0, normalizeSpanScopeText(r.toString()).length - leadingWs);
      } catch (_) {
        starts[i] = null;
      }
    });
  } catch (_) {}
  return starts;
}

function hoistBrFromInlineElements(rootEl) {
  if (!rootEl) return;
  const candidates = Array.from(
    rootEl.querySelectorAll(
      'p, div, li, blockquote, address, figcaption, h1, h2, h3, h4, h5, h6, caption, summary, dd, dt'
    )
  );
  candidates.forEach((block) => {
    // Never split table cells or elements inside table cells by <br> tags
    if (block.closest('td, th')) return;
    if (!block.querySelector('br')) return;

    let guard = 0;
    while (guard < 150) {
      guard++;
      const brList = Array.from(block.querySelectorAll('br'));
      const deepBr = brList.find((br) => br.parentElement && br.parentElement !== block);
      if (!deepBr) break;

      const inlineParent = deepBr.parentElement;
      const inlineTag = inlineParent.tagName.toLowerCase();
      if (['p', 'div', 'li', 'ul', 'ol', 'table', 'tbody', 'thead', 'tr', 'td', 'th', 'blockquote', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'].includes(inlineTag)) {
        break;
      }

      const afterClone = inlineParent.cloneNode(false);
      while (deepBr.nextSibling) {
        afterClone.appendChild(deepBr.nextSibling);
      }

      inlineParent.parentNode.insertBefore(deepBr, inlineParent.nextSibling);

      if (afterClone.childNodes.length > 0) {
        deepBr.parentNode.insertBefore(afterClone, deepBr.nextSibling);
      }

      if (inlineParent.childNodes.length === 0) {
        inlineParent.remove();
      }
    }
  });
}

function wrapBrSegments(rootEl) {
  if (!rootEl) return;
  hoistBrFromInlineElements(rootEl);
  const doc = rootEl.ownerDocument || document;
  const candidates = Array.from(
    rootEl.querySelectorAll(
      'p, div, li, blockquote, address, figcaption, h1, h2, h3, h4, h5, h6, caption, summary, dd, dt'
    )
  );
  candidates.forEach((p) => {
    // Never split table cells or any elements inside table cells (td, th) by <br> tags
    if (p.closest('td, th')) return;
    if (!p.querySelector('br')) return;
    if (p.querySelector('.gc-br-line')) return;

    // Only leaf containers (do not wrap if it contains other block containers)
    const hasChildBlock = Boolean(
      p.querySelector('p, div, li, blockquote, table, ul, ol, h1, h2, h3, h4, h5, h6, address, figcaption')
    );
    if (hasChildBlock) return;

    const childNodes = Array.from(p.childNodes);
    const segments = [];
    let currentNodes = [];

    childNodes.forEach((node) => {
      if (node.nodeType === 1 && node.tagName.toLowerCase() === 'br') {
        segments.push({ nodes: currentNodes, br: node });
        currentNodes = [];
      } else {
        currentNodes.push(node);
      }
    });
    segments.push({ nodes: currentNodes, br: null });

    // Filter to check if any segment has meaningful content
    const hasContent = segments.some((s) =>
      s.nodes.some((n) => n.nodeType === 1 || (n.nodeType === 3 && n.textContent.trim().length > 0))
    );
    if (!hasContent) return;

    p.innerHTML = '';
    p.setAttribute('data-gc-br-wrapped', 'true');

    segments.forEach((seg, idx) => {
      const isMeaningful = seg.nodes.some(
        (n) => n.nodeType === 1 || (n.nodeType === 3 && n.textContent.trim().length > 0)
      );
      if (isMeaningful) {
        const span = doc.createElement('span');
        span.className = 'gc-br-line';
        span.setAttribute('data-gc-line', String(idx));
        seg.nodes.forEach((n) => span.appendChild(n));
        p.appendChild(span);
      } else {
        seg.nodes.forEach((n) => p.appendChild(n));
      }
      if (seg.br) {
        p.appendChild(seg.br);
      }
    });
  });
}

function unwrapBrSegments(rootEl) {
  if (!rootEl) return;
  rootEl.querySelectorAll('.gc-br-line').forEach((span) => {
    const parent = span.parentNode;
    if (parent) {
      while (span.firstChild) {
        parent.insertBefore(span.firstChild, span);
      }
      span.remove();
    }
  });
  rootEl.querySelectorAll('[data-gc-br-wrapped]').forEach((el) => {
    el.removeAttribute('data-gc-br-wrapped');
  });
}

function extractBlocks(rootEl) {
  // Ensure any lines broken up by <br> tags are recognized as individual blocks
  wrapBrSegments(rootEl);
  const all = Array.from(rootEl.querySelectorAll(BLOCK_SELECTOR));
  return all
    .filter((el) => isLeafBlock(el) && !isFootnoteBoilerplateElement(el))
    .filter((el) => {
      // Images without alt text or with auto-generated alt text normally have no text to translate.
      // However, keep PDF side panel publication thumbnail images so they can be navigated and highlighted.
      if (el.tagName.toLowerCase() === 'img') {
        const isPdfSide = isPdfSidePanelElement(el);
        const alt = (el.getAttribute('alt') || '').trim();
        if (!isPdfSide && (!alt || isAutoGeneratedImageAlt(alt))) return false;
      }
      return true;
    })
    .map((el) => {
      let tag = el.tagName.toLowerCase();
      const isBrLine = el.classList.contains('gc-br-line');
      if (isBrLine && el.parentElement) {
        tag = el.parentElement.tagName.toLowerCase();
      }
      let attrTarget = 'text';
      if (tag === 'img') attrTarget = 'alt';
      else if (['input', 'textarea'].includes(tag) && el.hasAttribute('placeholder'))
        attrTarget = 'placeholder';
      else if (el.hasAttribute('aria-label')) attrTarget = 'aria-label';
      const brCount = el.querySelectorAll('br').length;
      let text = getBlockContent(el);
      if (tag === 'img' && isPdfSidePanelElement(el) && !text) {
        text = (el.getAttribute('alt') || '').trim() || (el.getAttribute('src') || 'Publication cover thumbnail');
      }
      const isCaption = tag === 'caption' || Boolean(el.closest && el.closest('caption'));
      const inTable = !isCaption && (Boolean(el.closest && el.closest('table, tbody, thead, tfoot, tr, td, th')) || ['td', 'th'].includes(tag));
      return {
        el,
        tag,
        attrTarget,
        text,
        spans: extractBlockSpans(el),
        hasBr: brCount > 0,
        brCount,
        inTable,
        isBrLine,
      };
    })
    .filter((b) => b.text.length > 0)
    .filter((b) => !isClassificationMarking(b.text))
    .filter((b) => !isPlainUrlText(b.text))
    .filter((b) => {
      if (b.tag === 'img' && isPdfSidePanelElement(b.el)) return true;
      return !isAutoGeneratedImageAlt(b.text);
    });
}

function tagElementAsSwapTarget(el, attributes = {}, classNames = []) {
  if (!el) return el;
  let targetEl = el;

  // If this element is an <li> that contains direct child sub-lists (<ul> or <ol>),
  // do NOT place the swap target / highlight boundary on the parent <li> itself,
  // because that would wrap and highlight all child lists and nested items.
  // Instead, isolate its direct text and inline nodes in a <span class="gc-li-content">
  // so that highlighting and navigation moves item-by-item (<li> to <li>).
  const tag = el.tagName ? el.tagName.toLowerCase() : '';
  if (tag === 'li') {
    const childLists = Array.from(el.querySelectorAll(':scope > ul, :scope > ol'));
    if (childLists.length > 0) {
      let contentSpan = el.querySelector(':scope > .gc-li-content');
      if (!contentSpan) {
        contentSpan = el.ownerDocument.createElement('span');
        contentSpan.className = 'gc-li-content';
        const nodesToMove = [];
        Array.from(el.childNodes).forEach((child) => {
          if (!childLists.includes(child) && child !== contentSpan) {
            nodesToMove.push(child);
          }
        });
        if (childLists[0]) {
          el.insertBefore(contentSpan, childLists[0]);
        } else {
          el.appendChild(contentSpan);
        }
        nodesToMove.forEach((n) => contentSpan.appendChild(n));
      }
      targetEl = contentSpan;
    }
  }

  for (const [k, v] of Object.entries(attributes)) {
    if (v !== undefined && v !== null) {
      targetEl.setAttribute(k, String(v));
    }
  }

  if (classNames && classNames.length) {
    targetEl.classList.add(...classNames);
  }

  return targetEl;
}

// A block that is entirely one anchor link (typically a table-of-contents item
// like <li><a href="#a1">Purpose</a></li>). Conversion wraps the whole French
// line in the English anchor because the Word text carries no hyperlink, so
// these are recorded in the Conversion tab — and must not also be reported as
// "missing" by the link audit, since the output does contain the link.
// Returns the fragment href, or null.
function wholeBlockAnchorHref(block) {
  if (!block) return null;
  const spans = block.spans || [];
  const links = spans.filter((s) => s.type === 'a' && s.href);
  if (links.length !== 1 || spans.length !== 1) return null;
  if ((block.text || '') !== (links[0].text || '')) return null;
  const href = (links[0].href || '').trim();
  return href.startsWith('#') ? href : null;
}

export {
  cleanCaptionTags,
  cleanThTags,
  extractBlockSpans,
  extractBlocks,
  getBlockContent,
  hoistBrFromInlineElements,
  isAutoGeneratedImageAlt,
  isClassificationMarking,
  isDecorativeOrAutoGeneratedElement,
  isLeafBlock,
  isPlainUrlText,
  spanType,
  tagElementAsSwapTarget,
  unwrapBrSegments,
  wholeBlockAnchorHref,
  wrapBrSegments,
};
