// Auto-generated imports
import {
  isPdfSidePanelElement,
} from './alignment.js';
import {
  extractBlocks,
  isAutoGeneratedImageAlt,
} from './block-utils.js';
import {
  splitDocxBlocksOnBr,
} from './constants.js';
import {
  condensedFrStat,
  docxFile,
  docxStat,
  docxStatWrap,
  dropzoneMain,
} from './dom-refs.js';
import {
  formatFrenchRootRelativeLink,
} from './french-url.js';
import {
  checkAlignReady,
  formatBlockCount,
} from './sources.js';
import {
  state,
} from './state.ts';
import {
  showToast,
} from './ui-toast.js';


function parseFrDocxHtml(rawDocxHtml, filename = 'Uploaded Document.docx') {
  const parser = new DOMParser();
  const doc = parser.parseFromString('<html><body></body></html>', 'text/html');
  doc.body.innerHTML = rawDocxHtml;

  // Clean auto-generated decorative shapes, alert box screenshots, and AI image artifacts from Word
  doc.body.querySelectorAll('img').forEach((img) => {
    if (isPdfSidePanelElement(img)) return;
    const alt = img.getAttribute('alt') || '';
    if (!alt || isAutoGeneratedImageAlt(alt)) {
      const parentP = img.closest('p');
      if (parentP && parentP.textContent.trim() === '') {
        parentP.remove();
      } else {
        img.remove();
      }
    }
  });

  // Format any links inside the French Word document DOM to root-relative
  doc.body.querySelectorAll('a[href]').forEach((a) => {
    const rawHref = a.getAttribute('href');
    if (rawHref) {
      a.setAttribute('href', formatFrenchRootRelativeLink(rawHref));
    }
  });

  // Split French blocks separated by <br> tags into individual paragraphs
  // to replicate the standard paragraph structure of the English HTML
  splitDocxBlocksOnBr(doc.body);

  const blocks = extractBlocks(doc.body);

  state.frDocxName = filename;
  state.frRawDocxHtml = doc.body.innerHTML;
  state.frBlocks = blocks;

  renderDocxStat(blocks.length, filename);
  checkAlignReady();
}

const DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
// 50 MB is generous for a Word manuscript yet small enough to keep the
// in-browser mammoth conversion responsive.
const MAX_DOCX_BYTES = 50 * 1024 * 1024;

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function getFileExtension(name) {
  const base = String(name || '').split(/[\\/]/).pop() || '';
  const idx = base.lastIndexOf('.');
  return idx >= 0 ? base.slice(idx + 1).toLowerCase() : '';
}

function isDocxFile(file) {
  if (!file) return false;
  const ext = getFileExtension(file.name);
  if (ext === 'docx') return true;
  // Some platforms report an empty MIME type on drag-drop; only treat the
  // official OOXML MIME as a pass when the extension check could not run
  // (e.g. a file with no extension saved straight out of Word).
  if (!ext && file.type === DOCX_MIME) return true;
  return false;
}

function resetDocxInput() {
  if (docxFile) docxFile.value = '';
}

function showDocxError(message, plainToast) {
  docxStatWrap.innerHTML = `
      <div class="filestat err">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4"><circle cx="12" cy="12" r="10"/><line x1="12" y1="12" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
        <span>${message}</span>
      </div>`;
  if (docxStat) docxStat.textContent = '0 blocks';
  setClearDocxEnabled(false);
  showToast(plainToast || 'That file could not be read as .docx', 6000);
}

function truncateDocName(name, max = 25) {
  if (!name) return '';
  if (name.length > max) {
    return name.slice(0, max) + '...';
  }
  return name;
}

function setClearDocxEnabled(on) {
  const btn = document.getElementById('clearDocxBtn');
  if (btn) btn.disabled = !on;
}

function renderDocxStat(count, filename) {
  const safeName = escapeHtml(truncateDocName(filename, 60));
  const fullName = escapeHtml(filename);
  if (!count) {
    docxStatWrap.innerHTML = `
      <div class="filestat err">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-4 h-4"><circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" x2="12" y2="12"/><line x1="12" x2="12" y1="16" x2="12.01" y2="16"/></svg>
        <span>No headings, paragraphs, or lists detected in ${safeName}</span>
      </div>`;
    if (docxStat) docxStat.textContent = '0 blocks';
    setClearDocxEnabled(false);
  } else {
    docxStatWrap.innerHTML = `
      <div class="filestat">
        <span title="${fullName}">${safeName}</span>
      </div>`;
    if (docxStat) docxStat.textContent = formatBlockCount(count);
    setClearDocxEnabled(true);
  }

  if (condensedFrStat) {
    if (!count) {
      condensedFrStat.textContent = '0 blocks';
      condensedFrStat.removeAttribute('title');
    } else {
      condensedFrStat.textContent = formatBlockCount(count);
      condensedFrStat.removeAttribute('title');
    }
  }

}

function clearDocxFile() {
  state.frBlocks = [];
  state.frDocxName = '';
  state.frRawDocxHtml = '';
  docxStatWrap.innerHTML = '';
  setClearDocxEnabled(false);
  if (docxFile) docxFile.value = '';
  if (docxStat) docxStat.textContent = '0 blocks';
  if (condensedFrStat) {
    condensedFrStat.textContent = '0 blocks';
    condensedFrStat.removeAttribute('title');
  }
  checkAlignReady();
}

async function handleDocxFile(file) {
  if (!file) return;
  const safeName = escapeHtml(file.name || 'Uploaded Document.docx');
  try {
    // Reject non-docx picks before touching mammoth so a legacy .doc, .pdf,
    // or .txt gets a helpful message instead of mammoth's zip error.
    const ext = getFileExtension(file.name);
    if (ext === 'doc') {
      dropzoneMain.textContent = 'Drop .docx here or click to browse';
      showDocxError(
        `<strong>${safeName}</strong> is a legacy .doc file, which cannot be parsed in the browser. Re-save it as .docx in Word (File &rarr; Save As &rarr; Word Document *.docx) and try again.`,
        'Legacy .doc files are not supported — re-save as .docx',
      );
      return;
    }
    if (!isDocxFile(file)) {
      dropzoneMain.textContent = 'Drop .docx here or click to browse';
      const hint = ext ? `“${escapeHtml('.' + ext)}” files` : 'Files without a .docx extension';
      showDocxError(
        `${hint} are not supported. Please choose a Word document ending in <strong>.docx</strong> (got <strong>${safeName}</strong>).`,
        'Please choose a .docx file',
      );
      return;
    }
    if (file.size === 0) {
      dropzoneMain.textContent = 'Drop .docx here or click to browse';
      showDocxError(
        `<strong>${safeName}</strong> is empty (0 bytes) and contains no document to parse.`,
        'That .docx file is empty',
      );
      return;
    }
    if (file.size > MAX_DOCX_BYTES) {
      dropzoneMain.textContent = 'Drop .docx here or click to browse';
      const mb = (file.size / (1024 * 1024)).toFixed(1);
      showDocxError(
        `<strong>${safeName}</strong> is ${mb} MB, over the ${MAX_DOCX_BYTES / (1024 * 1024)} MB in-browser limit. Try a smaller document.`,
        'That .docx is too large to parse in the browser',
      );
      return;
    }
    // Which stage we were in when it threw, so the error can say so.
    let docxStage = 'loading converter';
    dropzoneMain.textContent = `Reading ${file.name}...`;
    try {
      // Mammoth is only needed when a .docx is actually uploaded, so it loads
      // on demand and stays out of the initial bundle.
      const { default: mammoth } = await import('mammoth');
      docxStage = 'converting to HTML';
      const arrayBuffer = await file.arrayBuffer();
      // A .docx is a ZIP archive, so it must start with the PK magic bytes.
      // Catching a misnamed .doc/.pdf here avoids mammoth's cryptic
      // "Can't find end of central directory" failure.
      const header = new Uint8Array(arrayBuffer.slice(0, 4));
      const isZip = header.length >= 4 && header[0] === 0x50 && header[1] === 0x4b && (header[2] === 0x03 || header[2] === 0x05 || header[2] === 0x07) && (header[3] === 0x04 || header[3] === 0x06 || header[3] === 0x08);
      if (!isZip) {
        dropzoneMain.textContent = 'Drop .docx here or click to browse';
        showDocxError(
          `<strong>${safeName}</strong> does not look like a valid .docx file (missing ZIP header). If it was renamed from .doc or .pdf, re-save/export it as .docx in Word and try again.`,
          'That file is not a valid .docx',
        );
        return;
      }
      const result = await mammoth.convertToHtml({ arrayBuffer });
      if (!result || typeof result.value !== 'string' || !result.value.trim()) {
        dropzoneMain.textContent = 'Drop .docx here or click to browse';
        showDocxError(
          `No readable text was found in <strong>${safeName}</strong>. The document may be empty, password-protected, or contain only images.`,
          'No readable text found in that .docx',
        );
        return;
      }
      docxStage = 'parsing blocks';
      dropzoneMain.textContent = 'Drop .docx here or click to browse';
      parseFrDocxHtml(result.value, file.name);
    } catch (err) {
      // The generic "ensure it is a valid .docx" text is misleading when the
      // failure is our own code rather than a bad file, and it sent us looking in
      // the wrong place. Show which stage failed and the actual message: mammoth
      // rejecting the file, or parseFrDocxHtml/extractBlocks throwing on it.
      const stage = docxStage;
      const detail = escapeHtml((err && (err.message || String(err))) || 'unknown error');
      console.error(`Error parsing docx (stage: ${stage}):`, err);
      dropzoneMain.textContent = 'Drop .docx here or click to browse';
      showDocxError(
        `Failed to read Word document during <strong>${escapeHtml(stage)}</strong>: ${detail}`,
        `Failed to read .docx (${stage})`,
      );
    }
  } finally {
    // Always reset the <input> so picking the same file twice still fires
    // a change event. Without this, retrying an upload after an error — or
    // re-uploading the same document — silently does nothing.
    resetDocxInput();
  }
}

export {
  clearDocxFile,
  handleDocxFile,
  isDocxFile,
  parseFrDocxHtml,
  renderDocxStat,
  truncateDocName,
};
