// Auto-generated imports
import {
  isFootnoteContentBlock,
  isFootnoteElement,
  isFootnoteHeadingBlock,
} from './footnotes.js';
import {
  extractNumbersAndData,
  isHeadingTag,
} from './alignment.js';
import {
  issueSnippet,
} from './alignment-ops.js';
import {
  isAutoGeneratedImageAlt,
  wholeBlockAnchorHref,
} from './block-utils.js';
import {
  state,
} from './state.ts';


function normalizeQaText(text) {
  return (text || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

function isEnPlaceholderHref(href) {
  if (!href || typeof href !== 'string') return false;
  const t = href.trim();
  if (/^(#|mailto:|tel:|javascript:)/i.test(t)) return false;
  return /\/en\//i.test(t) || (/\/content\/canadasite\//i.test(t) && !/\/fr\//i.test(t));
}

function collectFootnoteNumberSet(blocks) {
  const set = new Set();
  (blocks || []).forEach((b) => {
    if (!b) return;
    const el = b.el && typeof b.el.querySelectorAll === 'function' ? b.el : null;
    if (el) {
      el.querySelectorAll('sup a.fn-lnk, a.fn-lnk, a[href^="#fn"], a[href^="#footnote-"], [id$="-rf"]').forEach((n) => {
        const href = (n.getAttribute && n.getAttribute('href')) || '';
        const id = (n.getAttribute && n.getAttribute('id')) || '';
        const text = (n.textContent || '').trim();
        const hrefMatch = href.match(/#(?:fn|footnote-)?(\d{1,3})/i);
        const idMatch = id.match(/^fn(\d{1,3})-rf$/i);
        const textMatch = text.match(/\b(\d{1,3})\b/);
        const num = (hrefMatch && hrefMatch[1]) || (idMatch && idMatch[1]) || (textMatch && textMatch[1]);
        if (num) set.add(String(parseInt(num, 10)));
      });
    }
    const raw = b.text || '';
    for (const m of raw.matchAll(/\[(\d{1,3})\]|\b(?:Note\s+de\s+bas\s+de\s+page|Footnote)\s+(\d{1,3})\b/gi)) {
      set.add(String(parseInt(m[1] || m[2], 10)));
    }
  });
  return set;
}

function findFirstFootnoteBlockIndex(blocks) {
  const idx = (blocks || []).findIndex((b) => {
    if (!b) return false;
    if (isFootnoteHeadingBlock(b) || isFootnoteContentBlock(b, blocks)) return true;
    const el = b.el && typeof b.el.querySelector === 'function' ? b.el : null;
    // No bare `sup` here: unit exponents (m³, ³²P) are content, not markers.
    if (el && (el.querySelector('.fn-lnk, a[href^="#fn"], a[href^="#footnote-"], [id$="-rf"]') || isFootnoteElement(el))) return true;
    return /\b(?:Note\s+de\s+bas\s+de\s+page|Footnote)\s+\d+\b|\[\d+\]/i.test(b.text || '');
  });
  return idx;
}

function findTableCellRunStarts() {
  const starts = [];
  let inRun = false;
  (state.enBlocks || []).forEach((b, idx) => {
    const inTable = Boolean(b && (b.inTable || b.tag === 'td' || b.tag === 'th'));
    if (inTable && !inRun) {
      starts.push(idx);
      inRun = true;
    } else if (!inTable) {
      inRun = false;
    }
  });
  return starts;
}


function computeTablesAndListsAudit() {
  const tables = [];
  const lists = [];

  // Parse English HTML to inspect table structure
  const rawHtml = state.enHtml || (state.enParsed && state.enParsed.rawHtml) || '';
  if (rawHtml) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(rawHtml, 'text/html');
    const tableEls = Array.from(doc.querySelectorAll('table'));
    tableEls.forEach((tbl, tIdx) => {
      const ths = Array.from(tbl.querySelectorAll('th'));
      const tds = Array.from(tbl.querySelectorAll('td'));
      const rows = Array.from(tbl.querySelectorAll('tr'));
      const hasCaption = !!tbl.querySelector('caption');
      const hasScope = ths.length > 0 && ths.every((th) => th.hasAttribute('scope') || th.hasAttribute('id'));
      const hasHeaders = tds.some((td) => td.hasAttribute('headers'));
      const colspans = Array.from(tbl.querySelectorAll('[colspan], [rowspan]'));

      tables.push({
        tableIndex: tIdx + 1,
        caption: hasCaption ? tbl.querySelector('caption').textContent.trim() : 'Standard Table',
        rowCount: rows.length,
        colHeaderCount: ths.length,
        cellCount: tds.length,
        hasScope,
        hasHeaders,
        complexSpans: colspans.length,
        wcagCompliant: hasScope || hasHeaders,
      });
    });

    const listEls = Array.from(doc.querySelectorAll('ul, ol, dl'));
    listEls.forEach((listEl, lIdx) => {
      const tag = listEl.tagName.toLowerCase();
      const items = Array.from(listEl.children).filter((c) => ['li', 'dt', 'dd'].includes(c.tagName.toLowerCase()));
      const isUnstyled = listEl.classList.contains('list-unstyled');
      lists.push({
        listIndex: lIdx + 1,
        tag,
        itemCount: items.length,
        isUnstyled,
        firstItem: items[0] ? items[0].textContent.trim().substring(0, 45) + '...' : 'Empty list',
      });
    });
  }

  return { tables, lists };
}

function computeQaDiffAudit() {
  const qaIssues = [];

  // Note: hyperlink findings live in the Links tab (computeLinkAudit) —
  // QA Diff no longer duplicates missing-link / kept-EN-URL rows.

  // 2. Footnote balance check
  const countFootnotesInHtml = (html) => {
    if (!html) return 0;
    const fnLinks = html.match(/<a[^>]*class=["'][^"']*fn-lnk[^"']*["'][^>]*>/gi) || [];
    if (fnLinks.length > 0) return fnLinks.length;
    const supRf = html.match(/<sup[^>]*id=["']fn\d+-rf["'][^>]*>/gi) || [];
    if (supRf.length > 0) return supRf.length;
    const wordFnLinks = html.match(/<a[^>]*href=["']#(?:footnote-|ftn)\d+["'][^>]*>/gi) || [];
    if (wordFnLinks.length > 0) return wordFnLinks.length;
    // Digit-only <sup> only counts when the document also carries footnote
    // definitions — otherwise every m³ / ³²P exponent would be a "footnote".
    const hasDefinitions = /<(?:dd|li|p|div|a)\b[^>]*\b(?:id|name)=["'](?:fn|ftn|footnote)[-_]?\d+["']/i.test(html)
      || /<a[^>]*\bname=["'](?:_?ftn|footnote-)\d+["']/i.test(html);
    if (hasDefinitions) {
      const supNumbers = html.match(/<sup[^>]*>\s*(?:<[^>]+>)*\s*\d+\s*(?:<\/[^>]+>)*\s*<\/sup>/gi) || [];
      if (supNumbers.length > 0) return supNumbers.length;
    }
    const bracketMatches = html.match(/\[\d+\]/g) || [];
    return bracketMatches.length;
  };

  const countFootnotesInBlocks = (blocks) => {
    if (!blocks || !blocks.length) return 0;
    let count = 0;
    blocks.forEach((b) => {
      const el = b && b.el && typeof b.el.querySelector === 'function' ? b.el : null;
      // No bare `sup` here: unit exponents (m³, cm²) are content, not markers.
      if (el && (el.querySelector('.fn-lnk, [id$="-rf"], a[href^="#fn"], a[href^="#footnote-"]') || isFootnoteElement(el))) {
        // A canonical citation is <sup id="fn7-rf"><a class="fn-lnk" href="#fn7">,
        // so a four-way union selector counts the sup (via [id$="-rf"]) AND the
        // anchor (via .fn-lnk and a[href^="#fn"]) — every note twice, and an
        // English/French mismatch was reported for documents that were correct.
        // Count anchors, then add only the -rf sups that hold no anchor.
        const anchors = el.querySelectorAll('.fn-lnk, a[href^="#fn"], a[href^="#footnote-"]').length;
        const sups = el.querySelectorAll('[id$="-rf"]').length;
        const nestedAnchors = el.querySelectorAll('[id$="-rf"] .fn-lnk, [id$="-rf"] a[href^="#fn"], [id$="-rf"] a[href^="#footnote-"]').length;
        count += Math.max(1, anchors + Math.max(0, sups - nestedAnchors));
      } else if (/\b(?:Note\s+de\s+bas\s+de\s+page|Footnote)\s+\d+\b/i.test(b.text || '') || /\[\d+\]/.test(b.text || '')) {
        count += (b.text.match(/\b(?:Note\s+de\s+bas\s+de\s+page|Footnote)\s+\d+\b|\[\d+\]/gi) || []).length;
      }
    });
    return count;
  };

  const enFnCount = Math.max(countFootnotesInHtml(state.enHtml), countFootnotesInBlocks(state.enBlocks));
  const frFnCount = Math.max(
    countFootnotesInHtml(state.frRawDocxHtml),
    countFootnotesInBlocks(state.frBlocks)
  );

  // Fallback headcount: only fires when no structured footnote numbers were detected
  // (the precise number-set check in section 8 supersedes this otherwise).
  if (enFnCount > 0 && enFnCount !== frFnCount && collectFootnoteNumberSet(state.enBlocks).size === 0 && collectFootnoteNumberSet(state.frBlocks).size === 0) {
    // Find the first block containing a footnote callout or footnote section to jump accurately
    let targetEnIndex = state.enBlocks.findIndex((b) => {
      if (isFootnoteHeadingBlock(b) || isFootnoteContentBlock(b, state.enBlocks)) return true;
      const el = b && b.el && typeof b.el.querySelector === 'function' ? b.el : null;
      if (el && (el.querySelector('.fn-lnk, a[href^="#fn"], [id$="-rf"]') || isFootnoteElement(el))) return true;
      return false;
    });
    if (targetEnIndex === -1) targetEnIndex = 0;

    let targetFrIndex = state.frBlocks.findIndex((b) => {
      if (isFootnoteHeadingBlock(b) || isFootnoteContentBlock(b, state.frBlocks)) return true;
      const el = b && b.el && typeof b.el.querySelector === 'function' ? b.el : null;
      if (el && (el.querySelector('.fn-lnk, a[href^="#fn"], [id$="-rf"], a[href^="#footnote-"]') || isFootnoteElement(el))) return true;
      if (/\b(?:Note\s+de\s+bas\s+de\s+page|Footnote)\s+\d+\b|\[\d+\]/i.test(b.text || '')) return true;
      return false;
    });
    if (targetFrIndex === -1) {
      const pair = state.alignPairs.find((p) => p.enIndex === targetEnIndex && !p.skip);
      targetFrIndex = pair && pair.frIndex !== null ? pair.frIndex : targetEnIndex;
    }

    qaIssues.push({
      type: 'fn_mismatch',
      severity: 'info',
      enIndex: targetEnIndex,
      frIndex: targetFrIndex,
      title: `Footnote Count (${enFnCount} EN vs ${frFnCount} FR detected)`,
      detail: `Ensure all footnote callouts (Note de bas de page) align with corresponding English footnotes.`,
      action: 'Verify Footnotes',
    });
  }

  // 3. Length divergence check (asymmetric thresholds; French runs ~15-20% longer).
  // Title-like blocks (headings, list items) diverge naturally, so they need more text to qualify.
  state.alignPairs.forEach((pair) => {
    const enB = state.enBlocks[pair.enIndex];
    const frB = state.frBlocks[pair.frIndex];
    if (!enB || !frB) return;
    const titleLike = isHeadingTag(enB.tag) || isHeadingTag(frB.tag) || enB.tag === 'li' || frB.tag === 'li';
    const minLen = titleLike ? 80 : 40;
    if (enB.text.length > minLen && frB.text.length > minLen) {
      const ratio = frB.text.length / enB.text.length;
      if (ratio > 2.0 || ratio < 0.5) {
        qaIssues.push({
          type: 'length_divergence',
          severity: 'info',
          enIndex: pair.enIndex,
          frIndex: pair.frIndex,
          title: `Block #${pair.enIndex + 1}: High text length difference (${Math.round(ratio * 100)}%)`,
          detail: `EN (${enB.text.length} chars): "${issueSnippet(enB.text, 50)}" vs FR (${frB.text.length} chars): "${issueSnippet(frB.text, 50)}"`,
          action: 'Inspect block',
        });
      }
    }
  });

  // 4. List format style adaptation notice (e.g. Word 1. / decimal to HTML a. / lower-alpha).
  // Severity 'notice': a verified confirmation, excluded from the QA Diff open count.
  state.alignPairs.forEach((pair) => {
    const enB = state.enBlocks[pair.enIndex];
    const frB = state.frBlocks[pair.frIndex];
    if (!enB || !frB) return;
    if (enB.tag === 'li' && frB.tag === 'li') {
      const enParentOl = enB.el && typeof enB.el.closest === 'function' ? enB.el.closest('ol') : null;
      if (enParentOl) {
        const isAlpha = enParentOl.classList.contains('lst-lwr-alph') || enParentOl.classList.contains('lst-upr-alph') || enParentOl.getAttribute('type') === 'a' || enParentOl.getAttribute('type') === 'A';
        const isRoman = enParentOl.classList.contains('lst-lwr-rmn') || enParentOl.classList.contains('lst-upr-rmn') || enParentOl.getAttribute('type') === 'i' || enParentOl.getAttribute('type') === 'I';
        if (isAlpha || isRoman) {
          const listType = isAlpha ? 'alphabetical (a, b, c...)' : 'Roman numeral (i, ii, iii...)';
          qaIssues.push({
            type: 'list_format_adapted',
            severity: 'notice',
            enIndex: pair.enIndex,
            frIndex: pair.frIndex,
            title: `Block #${pair.enIndex + 1}: List format adapted to ${listType}`,
            detail: `English HTML template applies <ol class="${enParentOl.className || 'type'}"> style (${listType}). The aligned French output inherits this structure while retaining translated text.`,
            action: 'Verified ✓',
          });
        }
      }
    }
  });

  // 5. Untranslated blocks: French text identical to English (skipped translation).
  state.alignPairs.forEach((pair) => {
    const enB = state.enBlocks[pair.enIndex];
    const frB = state.frBlocks[pair.frIndex];
    if (!enB || !frB) return;
    const enNorm = normalizeQaText(enB.text);
    const frNorm = normalizeQaText(frB.text);
    if (enNorm.length >= 12 && enNorm === frNorm && /[a-z]{4}/.test(enNorm)) {
      qaIssues.push({
        type: 'untranslated',
        severity: 'warn',
        enIndex: pair.enIndex,
        frIndex: pair.frIndex,
        title: `Block #${pair.enIndex + 1}: French text identical to English`,
        detail: `No translation detected — "${issueSnippet(enB.text, 60)}". Enter the French translation or confirm the English text is intentional.`,
        action: 'Translate block',
      });
    }
  });

  // Note: kept-EN-URL findings live in the Links tab (computeLinkAudit) —
  // QA Diff no longer duplicates them.

  // 6. Number consistency: doses, dates, percentages and figures that vanished in French.
  // Decimals always count; small integers only when 2+ are missing (months/years are often reworded).
  state.alignPairs.forEach((pair) => {
    const enB = state.enBlocks[pair.enIndex];
    const frB = state.frBlocks[pair.frIndex];
    if (!enB || !frB) return;
    if ((enB.text || '').length < 20) return;
    const enNums = extractNumbersAndData(enB.text);
    const frNums = extractNumbersAndData(frB.text);
    if (!enNums.size) return;
    const missing = [...enNums].filter((n) => !frNums.has(n));
    if (!missing.length) return;
    const significant = missing.filter((n) => n.includes('.') || n.length >= 3);
    const minor = missing.filter((n) => !n.includes('.') && n.length < 3);
    if (significant.length > 0 || minor.length >= 2) {
      qaIssues.push({
        type: 'number_mismatch',
        severity: 'warn',
        enIndex: pair.enIndex,
        frIndex: pair.frIndex,
        title: `Block #${pair.enIndex + 1}: Number(s) missing in French (${missing.join(', ')})`,
        detail: `EN contains ${missing.join(', ')} but the French translation does not. Verify doses, dates and figures.`,
        action: 'Check numbers',
      });
    }
  });

  // 7. Duplicate French content (copy-paste slips): adjacent identical blocks,
  // and one FR block aligned to multiple EN blocks (excluding legitimate <br> merges).
  for (let i = 1; i < (state.frBlocks || []).length; i++) {
    const prev = normalizeQaText(state.frBlocks[i - 1] && state.frBlocks[i - 1].text);
    const cur = normalizeQaText(state.frBlocks[i] && state.frBlocks[i].text);
    if (cur.length >= 20 && prev === cur) {
      const pair = (state.alignPairs || []).find((p) => p.frIndex === i && !p.skip);
      const enIdx = pair && pair.enIndex !== null
        ? pair.enIndex
        : Math.max(0, Math.min(i, (state.enBlocks || []).length - 1));
      qaIssues.push({
        type: 'duplicate_fr',
        severity: 'warn',
        enIndex: enIdx,
        frIndex: i,
        title: `Block #${enIdx + 1}: Duplicated French paragraph`,
        detail: `FR Word block #${i} and #${i + 1} are identical — "${issueSnippet(state.frBlocks[i].text, 60)}". Likely a copy-paste slip.`,
        action: 'Deduplicate',
      });
    }
  }
  {
    const frUse = {};
    (state.alignPairs || []).forEach((p) => {
      if (p.frIndex === null || p.skip) return;
      (frUse[p.frIndex] = frUse[p.frIndex] || []).push(p);
    });
    Object.keys(frUse).forEach((frKey) => {
      const users = frUse[frKey];
      if (users.length > 1 && !users.some((p) => p.groupedFrIndices && p.groupedFrIndices.length > 1)) {
        const first = users[0];
        qaIssues.push({
          type: 'duplicate_fr',
          severity: 'warn',
          enIndex: first.enIndex,
          frIndex: first.frIndex,
          title: `Block #${first.enIndex + 1}: Same French text used ${users.length}x`,
          detail: `EN blocks ${users.map((p) => `#${p.enIndex + 1}`).join(', ')} all point at the same French paragraph. Verify each translation is distinct.`,
          action: 'Deduplicate',
        });
      }
    });
  }

  // 8. Footnote number-set comparison (precise pairing, not just headcounts).
  {
    const enFnSet = collectFootnoteNumberSet(state.enBlocks);
    const frFnSet = collectFootnoteNumberSet(state.frBlocks);
    if (enFnSet.size > 0) {
      const missingInFr = [...enFnSet].filter((n) => !frFnSet.has(n));
      const extraInFr = [...frFnSet].filter((n) => !enFnSet.has(n));
      if (missingInFr.length > 0 || extraInFr.length > 0) {
        let targetEnIndex = findFirstFootnoteBlockIndex(state.enBlocks);
        if (targetEnIndex === -1) targetEnIndex = 0;
        let targetFrIndex = findFirstFootnoteBlockIndex(state.frBlocks);
        if (targetFrIndex === -1) {
          const pair = (state.alignPairs || []).find((p) => p.enIndex === targetEnIndex && !p.skip);
          targetFrIndex = pair && pair.frIndex !== null ? pair.frIndex : targetEnIndex;
        }
        const parts = [];
        if (missingInFr.length > 0) parts.push(`missing in French: ${missingInFr.join(', ')}`);
        if (extraInFr.length > 0) parts.push(`extra in French: ${extraInFr.join(', ')}`);
        qaIssues.push({
          type: 'footnote_numbers',
          severity: 'warn',
          enIndex: targetEnIndex,
          frIndex: targetFrIndex,
          title: `Footnote mismatch (EN [${[...enFnSet].join(', ')}] vs FR [${[...frFnSet].join(', ') || '—'}])`,
          detail: `Footnote callouts out of sync — ${parts.join('; ')}. Ensure every Note de bas de page aligns with its English footnote.`,
          action: 'Verify footnotes',
        });
      }
    }
  }

  // 9. Footnote placement log. Recognition and placement are kept apart on
  //    purpose. Recognition is binary and evidence-based — a citation carries a
  //    fn-lnk class, a #fn3 href or an fn3-rf id, or it is content — so it is
  //    reported as a fact and counts as open. Placement is inference on a French
  //    string: the marker went back in at a position derived from where the
  //    English citation stood, and nobody can tell from the output whether that
  //    was the right claim. Those rows are severity 'notice' — visible, and
  //    deliberately excluded from the open count, so a document that is correct
  //    is not reported as broken just because a guess was made and recorded.
  {
    (state.footnoteReport || []).forEach((entry) => {
      const enIndex = entry.enIndex === null || entry.enIndex === undefined ? 0 : entry.enIndex;
      const isPlacement = entry.kind === 'placement';
      qaIssues.push({
        type: isPlacement ? 'footnote_place' : 'footnote_recog',
        severity: isPlacement ? 'notice' : 'warn',
        enIndex,
        frIndex: entry.frIndex === null || entry.frIndex === undefined ? null : entry.frIndex,
        title: isPlacement
          ? `Footnote ${entry.num}: position inferred, not confirmed`
          : `Footnote ${entry.num}: recognition finding`,
        detail: entry.detail,
        action: isPlacement ? 'Confirm position' : 'Check note',
      });
    });
    (state.footnoteProblems || []).forEach((text) => {
      const enIndex = findFirstFootnoteBlockIndex(state.enBlocks);
      qaIssues.push({
        type: 'footnote_recog',
        severity: 'warn',
        enIndex: enIndex === -1 ? 0 : enIndex,
        frIndex: null,
        title: 'Footnote count differs between English and French',
        detail: text,
        action: 'Check note',
      });
    });
  }

  // 9. Table header accessibility: EN tables with no usable headers.
  {
    const rawHtml = state.enHtml || '';
    if (rawHtml) {
      try {
        const parser = new DOMParser();
        const doc = parser.parseFromString(rawHtml, 'text/html');
        const tableEls = Array.from(doc.querySelectorAll('table'));
        const cellRuns = findTableCellRunStarts();
        tableEls.forEach((tbl, tIdx) => {
          const ths = Array.from(tbl.querySelectorAll('th'));
          const scoped = ths.filter((th) => th.hasAttribute('scope') || th.hasAttribute('id'));
          const tdsWithHeaders = Array.from(tbl.querySelectorAll('td[headers]'));
          if (ths.length === 0 || (scoped.length === 0 && tdsWithHeaders.length === 0)) {
            const cap = tbl.querySelector('caption');
            const label = cap ? cap.textContent.trim().substring(0, 40) : `Table #${tIdx + 1}`;
            qaIssues.push({
              type: 'table_headers',
              severity: 'warn',
              enIndex: cellRuns[tIdx] !== undefined ? cellRuns[tIdx] : 0,
              frIndex: null,
              title: `Table "${label}": missing accessible headers`,
              detail: ths.length === 0
                ? 'No <th> header cells found. Screen readers cannot parse this table — add header row with scope="col".'
                : 'Header cells lack scope="col"/scope="row" (or headers="..."). Add scope attributes for WCAG 2.1 AA.',
              action: 'Add headers',
            });
          }
        });
      } catch (_) {}
    }
  }

  return qaIssues;
}

function computeLinkAudit() {
  const rows = [];
  let enIdSet = null;
  const getEnIds = () => {
    if (enIdSet) return enIdSet;
    enIdSet = new Set();
    try {
      const rawHtml = state.enHtml || '';
      if (rawHtml) {
        const parser = new DOMParser();
        const doc = parser.parseFromString(rawHtml, 'text/html');
        doc.querySelectorAll('[id]').forEach((el) => {
          const id = el.getAttribute('id');
          if (id) enIdSet.add(id);
        });
      }
    } catch (_) {}
    return enIdSet;
  };

  (state.alignPairs || []).forEach((pair) => {
    const enB = state.enBlocks[pair.enIndex];
    const frB = state.frBlocks[pair.frIndex];
    if (!enB || !frB) return;
    // Whole-block anchors (table-of-contents items) are carried into the
    // French output by conversion and recorded in the Conversion tab, so they
    // are not link findings. Reporting them here as "missing" was a false
    // positive — the output does contain the link.
    if (wholeBlockAnchorHref(enB)) return;
    const enLinks = (enB.spans || []).filter((s) => s.type === 'a' && s.href);
    const frLinks = (frB.spans || []).filter((s) => s.type === 'a' && s.href);
    if (!enLinks.length && !frLinks.length) return;
    const width = Math.max(enLinks.length, frLinks.length);
    for (let i = 0; i < width; i++) {
      const en = enLinks[i];
      const fr = frLinks[i];
      const enHref = (en && en.href) || '';
      const frHref = (fr && fr.href) || '';
      let status = 'ok';
      let note = 'Hyperlink carries over with a valid French URL.';
      if (enHref && !frHref) {
        status = 'missing';
        note = 'No French hyperlink — output keeps plain text or the EN URL placeholder.';
      } else if (frHref && isEnPlaceholderHref(frHref)) {
        status = 'en-url';
        note = 'French output keeps an English URL — replace with the French page URL.';
      } else if (enHref && enHref.startsWith('#') && !getEnIds().has(enHref.slice(1))) {
        status = 'anchor';
        note = 'EN anchor target not found in the English source.';
      } else if (frHref && frHref.startsWith('#') && !getEnIds().has(frHref.slice(1))) {
        status = 'anchor';
        note = 'FR anchor target not found (ids carry over from English).';
      }
      rows.push({
        enIndex: pair.enIndex,
        frIndex: pair.frIndex,
        enAnchor: (en && en.text) || '',
        enHref,
        frAnchor: (fr && fr.text) || '',
        frHref,
        status,
        note,
      });
    }
  });

  return { rows, openCount: rows.filter((r) => r.status !== 'ok').length };
}

function computeHeadingsAudit() {
  const enHeads = [];
  const frHeads = [];
  (state.enBlocks || []).forEach((b, i) => {
    if (b && isHeadingTag(b.tag)) enHeads.push({ level: parseInt(b.tag[1], 10), text: b.text, enIndex: i });
  });
  (state.frBlocks || []).forEach((b, i) => {
    if (b && isHeadingTag(b.tag)) frHeads.push({ level: parseInt(b.tag[1], 10), text: b.text, frIndex: i });
  });
  const issues = [];

  const enH1 = enHeads.filter((h) => h.level === 1);
  if (enHeads.length > 0 && enH1.length !== 1) {
    issues.push({
      type: 'h1', severity: 'warn',
      enIndex: (enH1[0] || enHeads[0]).enIndex, frIndex: null,
      title: enH1.length === 0 ? 'No H1 in English source' : `Multiple H1s in English source (${enH1.length})`,
      detail: 'Canada.ca pages need exactly one H1. Fix the source HTML heading structure.',
      action: 'Fix heading',
    });
  }
  const frH1 = frHeads.filter((h) => h.level === 1);
  if (frHeads.length > 0 && frH1.length !== 1) {
    const jumpFr = (frH1[0] || frHeads[0]).frIndex;
    const pair = (state.alignPairs || []).find((p) => p.frIndex === jumpFr && !p.skip);
    issues.push({
      type: 'h1', severity: 'warn',
      enIndex: pair && pair.enIndex !== null ? pair.enIndex : 0, frIndex: jumpFr,
      title: frH1.length === 0 ? 'No H1 in French output' : `Multiple H1s in French output (${frH1.length})`,
      detail: 'The French output must mirror a single-H1 structure.',
      action: 'Fix heading',
    });
  }

  const checkSkips = (heads, lang) => {
    for (let i = 1; i < heads.length; i++) {
      if (heads[i].level > heads[i - 1].level + 1) {
        const isEn = lang === 'en';
        const jumpEn = isEn ? heads[i].enIndex : 0;
        const jumpFr = isEn ? null : heads[i].frIndex;
        issues.push({
          type: 'skip', severity: 'warn',
          enIndex: jumpEn, frIndex: jumpFr,
          title: `Skipped heading level (${lang.toUpperCase()}): H${heads[i - 1].level} → H${heads[i].level}`,
          detail: `"${issueSnippet(heads[i].text, 60)}" — skipped levels break screen-reader navigation (WCAG 1.3.1).`,
          action: 'Fix level',
        });
      }
    }
  };
  checkSkips(enHeads, 'en');
  checkSkips(frHeads, 'fr');

  if (enHeads.length > 0 && frHeads.length > 0 && enHeads.length !== frHeads.length) {
    issues.push({
      type: 'parity', severity: 'warn',
      enIndex: enHeads[0].enIndex, frIndex: frHeads[0].frIndex,
      title: `Heading count differs (EN ${enHeads.length} vs FR ${frHeads.length})`,
      detail: 'Every English heading needs exactly one French counterpart in the same order.',
      action: 'Align headings',
    });
  }

  return { en: enHeads, fr: frHeads, issues, openCount: issues.length };
}

function computeAltAudit() {
  const images = [];
  (state.enBlocks || []).forEach((b, i) => {
    if (!b || b.tag !== 'img') return;
    const el = b.el;
    const src = (el && el.getAttribute && el.getAttribute('src')) || '';
    const alt = ((el && el.getAttribute && el.getAttribute('alt')) || '').trim();
    let status = 'ok';
    let note = 'Alternative text present — carries into the French output.';
    if (!alt) {
      status = 'missing';
      note = 'No alternative text — screen readers skip this image. Add alt text or confirm it is decorative.';
    } else if (isAutoGeneratedImageAlt(alt)) {
      status = 'auto';
      note = 'Word/CMS boilerplate alt text — rewrite it meaningfully or empty it for decorative images.';
    }
    images.push({ enIndex: i, src, alt, status, note });
  });
  return { images, openCount: images.filter((im) => im.status !== 'ok').length };
}

export {
  computeAltAudit,
  computeHeadingsAudit,
  computeLinkAudit,
  computeQaDiffAudit,
  computeTablesAndListsAudit,
};
